### ISSUE TITLE
multiple data sources?

### ISSUE THREAD

**Issue by robstewart57** [dvcama/LodLive#1]
Is it possible to point LodLive at multiple data sources?

It'd excellent to have the ability to point LodLive at multiple SPARQL endpoints, and perhaps also multiple RDF files. This may slow down the interface, but could add some useful functionality.

Scenario: In a foaf.rdf file, someone has a number of foaf:topic_interest triples. Some are pointing at dbpedia resources, others FreeBase resources, and others are Yago resources. It'd be great if within LodLive, a user can click any one of the foaf:topic_interest properties, and the 3 SPARQL endpoints for dbpedia, freebase and yago are all queries for the URI object of the foaf:topic_interest triple.

This'd allow people to point LodLive an .rdf file to begin with.. and "walk away" from it in various directions.. regardless of the choice of resource namespaces used.

Is this a feasible and sensible idea?

**Comment by dvcama** [comment]
and 7 years later I'm closing this issue:

lodlive works exactly as you described :)
