### ISSUE TITLE
user/passw for digest protected LD Endpoints ?

### ISSUE THREAD

**Issue by redskate** [dvcama/LodLive#18]
Hi

my compliments for the very nice visualisation!!!

My Endpoints are DIGEST secured. How can I insert in the profile the credentials of a technical user to access the endpoint?

Thanks in advance
Regards

**Comment by redskate** [comment]
:) Ho riaperto il nodo "issues" e constatato che zero risposte a 5 - 6 issues indicano che non viene proprio guardato "assiduamente" ... ;)

Buon lavoro

**Comment by dvcama** [comment]
Hi, 

lodlive is a "pure" client side application (no server component) so I think that you have to use a proxy able to do the authentication for the client but it depends... 

usually how do you access the sparql endpoint via browser?

**Comment by redskate** [comment]
Hi Diego Valerio

thank you for writing back. 

Every SPARQL endpoint serves with or without authentication.

In one of my projects the endpoint is served by a DIGEST secured tomcat.

Your nice lib is running when there is no need of authentication.

Hope I answered your question?

Regards

**Comment by dvcama** [comment]
Nope :)

Lodlive is client side so if you login in your tomcat and then use Lodlive to navigate the resources published on that tomcat it should work fine

If you want to hide to the user the password you have to use a proxy, alternatively you could hardcode in the sparql URI the credentials like http://foo:baar@sparql.com

**Comment by dvcama** [comment]
Ps I don't now if DIGEST allow you to hardcode the credentials into the uri...

**Comment by redskate** [comment]
Thank you for that, Valerio

I think you (lodlive) should seriously think on providing an access framework to secured LinkedData repositories. Some time linked data is not so "open" as we all wish ... there are copyrights, different levels of access. I mean, in case you want to sell it.

Another very important point for lodlive:
I noticed that all data handled by this "cliend side" app go through a server "regesta" and back to browser. In case the repository be only accessible throuch HTTPS this could block lodlive because of the "mixed contents" policy.

If you like we can have a skype on all this and more ;)

Regards
Fabio

**Comment by dvcama** [comment]
let me be clear on this, LodLive is client side, you can look up at the code and check what happen, or you can just trust me because I developed it

the web of data is a mess
* data violating the W3C recommendations
* data have not a sparql endpoint on http://yourdomain.com/sparql (and you have not customized lodlive to let it know where your sparql endpoint is)
* publications don't support jsonp calls
* etc...

LodLive (on the web site) uses a proxy to leverage that issues and demonstrate the power of the web of data, if you download a copy of it you don't have to use any proxy

I don't want to make money with lodlive, thank you

**Comment by redskate** [comment]
Hi Diego

(Actually we could exchange in Italian since I am italian - too).

Thank you for your message!!  

I find lodlive ***very*** nice - Just in these days I wanted to develop myself one similar tool and discovered in a blog lodlive.  

Regarding the code - yes it is javascript - but it takes me some time to reverse engineer all… it is quite deep programmed.
I could find out in the profile the point where a default endpoint was pointing at regesta, I developed my own resource proxy endpoint and now I am happy ;)

I fully understand your decision of using a regesta proxy (even when, technically speaking, a javascript proxy could be quite faster). As we all know there is always something to improve…

The (my) HTTPS issues with Digest access are central to me currently, that is why I was asking. I did not find jet the way to solve them integrally.

1) HTTPS: If the tool is running on HTTPS it will make some calls to HTTP taken from the LD data. This will generate a mixed content clause. ( I have still to figure out why this is like this) - as an example when I was using the Linked Data of the GETTY thesaurus under HTTPS the browser console threw:
12:47:44.435 Loading of mixed contents "http://vocab.getty.edu/sparql?output=json&format=application/json&timeout=0&query=select%20*%20where%20%7B%3Fa%20%3Fb%20%3Fc%7D%20LIMIT%201&callback=lodlive" [^] was blocked.1 jquery.jsonp-2.4.0.min.js:3:0 

2) Authentication - I will try your method of putting user/passwd in the url. Will this run for javascript… Javascript has some predisposed authentication methods - http://tools.ietf.org/html/rfc2617 for digest but I have to figure out where in the js code to put the authentication.

So you do not want to make money with your nice viz tool? Maybe somebody else wants? 

I am doing with lodlive what I whish/need other people would do with my site … -> I was thinking of promoting lodlive on my website - after having taken on board the colleagues of http://metreeca.it - what about it ?

Take a look at http://semweb.ch and find my email address. Just in case we can continue personally.

Buona giornata
Fabio

-- 
GMAIL
Sent with Airmail

On 8 August 2015 at 15:05:13, Diego Valerio Camarda (notifications@github.com) wrote:

let me be clear on this, LodLive is client side, you can look up at the code and check what happen, or you can just trust me because I developed it

the web of data is a mess

data violating the W3C recommendations
data have not a sparql endpoint on http://yourdomain.com/sparql (and you have not customized lodlive to let it know where your sparql endpoint is)
publications don't support jsonp calls
etc...
LodLive (on the web site) uses a proxy to leverage that issues and demonstrate the power of the web of data, if you download a copy of it you don't have to use any proxy

I don't want to make money with lodlive, thank you
