### ISSUE TITLE
Empty node on SKOS content

### ISSUE THREAD

**Issue by redskate** [dvcama/LodLive#19]
HI 

I am using since yesterday lodlive on some thesauri like GETTY and it is working well!

I would like to use lodlive to browse a thesaurus in SKOS format like in http://82.192.234.100:25818/bigdata/namespace/mb_zhdk_alle_thesauri_noinf/sparql/ 

I have configured this endpoint in the properties with

```
    'LODZ mb_zhdk_alle_thesauri_noinf' : {
        description : {
            en : 'mb_zhdk_alle_thesauri_noinf (unprotected)'
        },
        useForInverseSameAs : false,
        endpoint : 'http://82.192.234.100:25818/bigdata/namespace/mb_zhdk_alle_thesauri_noinf/sparql/',
        examples : [{
            label : 'Kultur',
            uri : 'http://lodzh.org/ZHDKThesaurus/194'
        }]
    },
```

When I position lodlive on http://lodzh.org/ZHDKThesaurus/194 - which is a valid entity descriptor inside that endpoint - it should show the SKOS entity associated with that descriptor.

Unfortunately lodlive does not show anything - just a node with the URI and the node is not expandable.

Clicking on "more info" I get
no endpoint configured for the resource, generating temporary graph
SELECT DISTINCT \* WHERE {http://lodzh.org/ZHDKThesaurus/1960 ?property ?object. FILTER(?property != http://dbpedia.org/ontology/wikiPageWikiLink)} ORDER BY ?property

What does this have to do with http://dbpedia.org/ontology/wikiPageWikiLink ???

Any idea why this is so?

Thank you very much in advance
Regards

**Comment by dvcama** [comment]
4 years later:

` 'LODZ mb_zhdk_alle_thesauri_noinf' : { `
should be
` 'http://lodzh.org' : { `
