### ISSUE TITLE
No LOD visualisation without http://labs.regesta.com/resourceProxy/ ?

### ISSUE THREAD

**Issue by redskate** [dvcama/LodLive#20]
Hello again (one last time)

I have loaded a GETTY thesaurus into a bigdata rdf store and I can browse it from inside lodlive.

From an analisys of the javascript calls issued by lodlive I noticed a call to

http://labs.regesta.com/resourceProxy/?uri=http%3A%2F%2Fvocab.getty.edu%2Faat%2Fsource%2F2000087067&query=SELECT%20DISTINCT%20*%20WHERE%20{%3Chttp%3A%2F%2Fvocab.getty.edu%2Faat%2Fsource%2F2000087067%3E%20%3Fproperty%20%3Fobject.%20FILTER%28%3Fproperty%20!%3D%20%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FwikiPageWikiLink%3E%29}%20ORDER%20BY%20%3Fproperty&callback=lodlive

How is lodlive really functioning? Is lodlive only functioning because it calls http://labs.regesta.com/resourceProxy/ ? Why does it have to call it ? Lodlive was supposed (I think) to work with an LOD endpoint, not needing any further repository ...

I would appreciate very much your response here

Thank you very much
Regards

**Comment by redskate** [comment]
Hello

I think I can answer to my question: labs.regesta.com/resourceProxy is the real processor of lodlab. This was your decision, data come from the browser down to regesta which performs the query and up again to the browser. 

A pity for mixed contents! I am running lodlive in https mode, the call to regesta is in http mode... and thus blocked by the browser ... 

Maybe this beeing a hint for allowing https on regesta resourceProxy server????

I know https is slow, but also the idea to redirect data to a server might be slow ... ;)

Thank you
Regards

**Comment by dvcama** [comment]
labs.regesta.com/resourceProxy is used to fix some issues with the published data, if you look at the output of the call you will see that the response is just a sparql json result

it is used when lodlive doesn't know which is your sparql endpoint or if your publication has some issues  (jsonp, etc.)
