### ISSUE TITLE
Too many language labels

### ISSUE THREAD

**Issue by roland-c** [dvcama/LodLive#21]
Hi,
Is there a way to specify the preferred language in LodLive?
Consider this : http://lod.kb.nl/LodLive/?http://viaf.org/viaf/64013650
Some resources contain too many language labels to fit into the cicle.

Thanks,
Roland

**Comment by dvcama** [comment]
it's pretty strange, labels should be ellipsed
look at http://en.lodlive.it/?http://dbpedia.org/resource/Rome
as you pointed out something is wrong with http://en.lodlive.it/?http://viaf.org/viaf/64013650 I'll check it

**Comment by dvcama** [comment]
done!
