### ISSUE TITLE
LodLive's sending requests to external proxies which is slowing things down

### ISSUE THREAD

**Issue by trevorlazarus** [dvcama/LodLive#25]
We've LodLive and LodView setup on a VM on Google Cloud, LodView loads fast, but LodLive takes much longer to load a resource.

I analysed the network traffic and LodLive seems to be sending requests to : 

data.camera.it/sparql?
data.acs.benicultural.it/sparql?
data.cur.it/sparql?

and a few others, is there a way to fix this, I noticed the linkedjazz instance of LodLive is much faster.

**Comment by dvcama** [comment]
Absolutely, go to lodlive.profile.js and change all
useForInverseSameAs:true to useForInverseSameAs:false

Let me know when your data are published ;)

Bye

Il Gio 10 Mar 2016 07:05 Trevor Lazarus <notifications@github.com> ha
scritto:

**Comment by trevorlazarus** [comment]
Thank you so much, I've changed all and it's made things way faster :) 

There is still something wrong with my SPARQL proxy, I've tried with LodView and Trifid-ld, it seems that the fallback resourceProxy at labs dot regesta is doing the job for me, I hope to get things fixed, I would also like to share some links with you as to why and how we are using both LodLive and LodView, is there an email address I can reach you on?

**Comment by dvcama** [comment]
Yes info@lodlive.it

The proxy is doing your job because you probably didn't configure your own
endpoint on lodlive.profile

I apologise for the lack of documentation, write me an email if you need
more help

Il Gio 10 Mar 2016 09:17 Trevor Lazarus <notifications@github.com> ha
scritto:

**Comment by trevorlazarus** [comment]
Hey, thanks for the info, I will sit tonight and configure everything properly.
No worries about the documentation, I will email you once everything is setup and I can proudly show off our datasets using LodLive and LodView
