### ISSUE TITLE
For some resources LodLive loads a black ball sometimes

### ISSUE THREAD

**Issue by tr3vr** [dvcama/LodLive#27]
When I try to open some resources, LodLive says "error: endpoint not available", any advice would be great. Thanks
![screen shot 2016-03-21 at 12 12 08 pm](https://cloud.githubusercontent.com/assets/11920074/13912041/a79a419c-ef5e-11e5-9968-86d59f8e9a44.png)

**Comment by dvcama** [comment]
it could happen for different reasons... I need more info or an access to try by myself

**Comment by tr3vr** [comment]
Okay, thanks. I will try to reproduce the error, it only seems to happen when too many resources are opened.

**Comment by dvcama** [comment]
it could be that your sparql endpoint takes more then 30 seconds to return the data, you can try to rise the timeout in lodlive.core.js
