### ISSUE TITLE
Inverse relations don't show the link 

### ISSUE THREAD

**Issue by tr3vr** [dvcama/LodLive#28]
Inversely related resources show up, but the links that connect them do not show up. Am I doing something wrong?

![screen shot 2016-03-21 at 12 12 41 pm](https://cloud.githubusercontent.com/assets/11920074/13912078/1017fb92-ef5f-11e5-92d9-a34e5d68b44e.png)

**Comment by dvcama** [comment]
the numbers of relationship in the resource "Number 4/2016" are more then the SPARQL limit set in the configuration file, check the query 
![image](https://user-images.githubusercontent.com/1757457/54863444-abf95280-4d40-11e9-961b-17be8c87cb61.png)
![image](https://user-images.githubusercontent.com/1757457/54863453-c16e7c80-4d40-11e9-9210-f885399158c2.png) 
see the 100 in the second query? 

the limit of the collected properties can be changed here https://github.com/dvcama/LodLive/blob/master/js/lodlive.profile.js#L17 (in your local copy of lodlive)
