### ISSUE TITLE
endpoints other than virtuoso

### ISSUE THREAD

**Issue by turbomam** [dvcama/LodLive#32]
Is LodLive expected to work with triplestores other than virtuoso?  I have downloaded the project from github and installed it on a server that has virtuoso, stardog and blazegraph.  It's working well with virtuoso but not the others.  All of them are responsive to CURL requests, even from remote hosts.

I see some references to sesame endpoint and proxies, like this for http://data.linkedmdb.org
                        endpointType : 'sesame',
                        proxy : 'http://lodview.it/simple-proxy/resourceProxy/',
                        endpoint : 'http://data.linkedmdb.org/sparql',

But I don't understand what endpoints are supported or what the proxy does.

Can you recommend a way to trace my failed attempts?  I don't see anything in my webserver's error log.

**Comment by dvcama** [comment]
LodLive is just made of javascript so, if you want it to work without the help of a proxy (that will handle for you the content negotiation), you need to be sure that your endpoint supports:

**JSONP**
you cannot do anything about JSONP (without a proxy) if your endpoint doesn't support it

**content negotiation override via URL parameter** 
virtuoso supports it via format=application/sparql-results+json
e.g. 
http://dbpedia.org/sparql?query=select+distinct+%3FConcept+where+%7B%5B%5D+a+%3FConcept%7D+LIMIT+100&format=application%2Fsparql-results%2Bjson   
according to this https://wiki.blazegraph.com/wiki/index.php/REST_API blazegraph should support it too

to test JSONP just add "callback" after the url 
e.g. 
http://dbpedia.org/sparql?query=select+distinct+%3FConcept+where+%7B%5B%5D+a+%3FConcept%7D+LIMIT+100&format=application%2Fsparql-results%2Bjson&callback=sdsdsdsdsdsd

_endpointType : 'sesame',_ is there to bound a specific type of endpoint to a specific group of additional URL parameters (see _sesame : 'Accept=application/sparql-results%2Bjson'_
 at the the bottom of the configuration file) 

anyway this is the simple proxy I use
https://github.com/dvcama/resource-to-sparqlresult let me know if you need any help with that

you can write me at info@lodlive.it if there is any chance to access your installation
