### ISSUE TITLE
example of browsing a local sparql endpoint?

### ISSUE THREAD

**Issue by darrencruse** [dvcama/LodLive#33]
Sorry for what's probably an extremely simple question but I'm having trouble pointing en.lodlive.it at my locally running virtuoso's sparql endpoint (using the "Insert URI" field on the home page).

It seems like I've (maybe?) gotten close to it working by giving the following url, but when I roll over the circle it says "resource not found" and won't let me select any linked nodes.  

Yet when I click the hyperlink in the middle of the circle it is getting data back for the sparql query.

Here's my URI: 
```
http://localhost:8890/sparql?query=select+%2A+where+%7B%3Fsubject+%3Fpredicate+%3Fobject%7D&default-graph-uri=https://velocity.ag/field-reference-data
```

**Comment by crockct** [comment]
I would also love this functionality. 
I ran into the same problem, and had some luck by hard-coding my endpoint in lodlive.core.js at 		```
guessingEndpoint : function(uri, onSuccess, onFail) {
			var base = "my endpoint here";
			//var base = uri.replace(/(^http:\/\/[^\/]+\/).+/, "$1");
```

**Comment by redskate** [comment]
no will to answer here?

**Comment by dvcama** [comment]
I hope you fixed this after 2 years!
there is an example here
https://github.com/dvcama/LodLive/blob/master/js/lodlive.profile-localhost-example.js

here the part that matters  (you cannot do that with the online version, the configuration file is shared among all the users)

```/*matching all the requested URIs*/  
		'http://' : {
			description : {
				en : 'just a test'
			},
			useForInverseSameAs : true,
			endpoint : 'http://localhost:8890/sparql' ]
		}
