### ISSUE TITLE
not working with https

### ISSUE THREAD

**Issue by giagabriele** [dvcama/LodLive#36]
https://github.com/dvcama/LodLive/blob/e90f5887cdec2bf347597c33653504cdf4e4e01f/js/lodlive.core.js#L134

Lodlive not work with https url, should be:
`var base = uri.replace(/(^http[s]{0,1}:\/\/[^\/]+\/).+/, "$1"); `

**Comment by dvcama** [comment]
done
https://github.com/dvcama/LodLive/blob/master/js/lodlive.core.js#L134
thank you for pointing it out
