### ISSUE TITLE
inverse relations doesn't shown

### ISSUE THREAD

**Issue by simonegasperoni** [dvcama/LodLive#39]
I cannot view the inverse arcs by the public lodview
http://lodlive.it/?https://sparql-noipa.mef.gov.it/resources/Place/F839

but I can see the inverse arcs if I download lodlive and execute it 
file:///C:/Users/s.gasperoni/Desktop/LodLive-master/LodLive-master/app_en.html?https://sparql-noipa.mef.gov.it/resources/Place/F839
locally on my laptop

why?
thanks

**Comment by dvcama** [comment]
I have just updated lodlive.it with the latest code version, it should work now
