### ISSUE TITLE
Add authorization header

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [dvcama/LodLive#40]
I'm testing a local SPARQL endpoint that requires an `Authorization` header. Is it possible to add the header at `lodlive.profile.js`? If so, can you provide any examples please?

**Comment by dvcama** [comment]
No, it is not possible. 
LodLive uses JSONP call to handle Cross origin requests limitations... you cannot add any Authorization header to jsonp calls, what about a proxy? 
you can use apache to convert a request parameter (that can be added in lodlive's configuration) into an Header
https://dino.ciuffetti.info/2015/11/http-request-header-query-string-parameter-apache-reverse-proxy/

**Comment by mikel-egana-aranguren** [comment]
OK, I will try the proxy approach, thanks.

The link you provided is not working though
