### ISSUE TITLE
Support for hash url

### ISSUE THREAD

**Issue by ghirardinicola** [dvcama/LodLive#9]
Url che hanno un # non sono correttamente visualizzate.
Vorrei ad esempio navigare su risorse di questo tipo : http://culturaitalia.it/pico/thesaurus/4.1#teatro
Probabilmente la soluzione potrebbe passare dal encodare l'hash  infatti importando il suddetto dataset e mettendo nell'url http://culturaitalia.it/pico/thesaurus/4.1%23teatro la risorsa viene correttamente visualizzata.

**Comment by AlexanderWillner** [comment]
I think this issue can be closed now (see merged commit).
